version: "3"
volumes:
  works:
    external:
      name: ubudev_works
  snaba-front:
    external:
      name: snaba-front_app
services:
  server:
    image: lsyncd/server:dev
    build:
      context: .
    volumes:
      - "works:/works"
      - "snaba-front:/snaba-front:nocopy"
